### ISSUE TITLE
Improve user-search and filtering

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#229]
We got new design for how to search for processes with users.
![image](https://user-images.githubusercontent.com/3164065/138650337-41c03860-6b1c-4034-8b19-c522c739cec7.png)

**Requirements**:
- [ ] filter processes on one or several users
- [ ] search for users to filter on
- [ ] the filter should use AND-logic. For example: selecting two users will display the processes where both those two users have access.

Back-end
- [x] new user search endpoint. (search on shortname untill #197 #148)
- [x] New user-filter-param for processes 
- [x] Remove `q-user-search-functionality`

Front-end
- [x] Implement new design and functionality (@Linedueo awaiting design) 

## TODO How to test

Fixes #226

**Comment by SjoenH** [comment]
@Linedueo Hi! Could you add the new design for filtering on users here?

**Comment by Linedueo** [comment]
<img width="724" alt="Skjermbilde 2021-10-19 kl  15 53 58" src="https://user-images.githubusercontent.com/74361011/137924374-6aa308b0-540b-4228-9133-5b23392547e3.png">
We can re-use the component for filter on label for the filter on user. @SjoenH

**Comment by SjoenH** [comment]
:wave: @Magos Did you make a user-search endpoint?

**Comment by Magos** [comment]
@SjoenH Yes, [this is the endpoint](https://vsm-api-dev.azurewebsites.net/swagger/index.html#operations-UserAccess-get_api_v_api_version__useraccess_usersearch) for user search/listing.

**Comment by SjoenH** [comment]
@Magos I sent you a message about this, but putting it here as well.

Do we have an endpoint to get the userName for a user? I can only find `userName` -> `pkUser`, and not `pkUser` -> `userName`.

**Comment by Magos** [comment]
[New endpoint for this](https://vsm-api-test.azurewebsites.net/swagger/index.html#operations-Task-SolveTaskForObject) added in the version on dev and test.

**Comment by SjoenH** [comment]
@ntorsen Ready for testing! :muscle: https://web-vsm-test.radix.equinor.com/processes?orderBy=modified&user=2&rl=2

**Comment by SjoenH** [comment]
I spoke too soon. @Magos we have cors issue for the user-search endpoint in test

**Comment by knudsvik** [comment]
@SjoenH We got feedback on a user search bug yesterday: #353. I guess that bug is not worth fixing since this feature will enhance the user search and is close to release anyway? In this release you should probably change the text in the search field if the user search is removed.. 

![image](https://user-images.githubusercontent.com/25986427/150301523-5bcd74cf-89a6-471e-8a94-5e5d948b4b0a.png)

**Comment by SjoenH** [comment]
@Magos we should consider removing username search from the free-text-query

**Comment by SjoenH** [comment]
@Magos ![image](https://user-images.githubusercontent.com/3164065/150357524-06672efa-38ee-43dd-ba60-9b90b20f853b.png)
- [ ] Fix cors issue

**Comment by Magos** [comment]
The `q` parameter hasn't supported user search for a while now, so that part is already changed. Is there any back-end work needed to fix the CORS issue, @SjoenH ?

**Comment by SjoenH** [comment]
@Magos Yes. We still need back-end fix for CORS. But really weird that it is only for that one endpoint… :thinking:

**Comment by SjoenH** [comment]
Never mind @Magos. Looks like I'm missing an `/` in the request url...

**Comment by SjoenH** [comment]
Fixed :white_check_mark: 
@ntorsen ready for testing https://web-vsm-test.radix.equinor.com

**Comment by SjoenH** [comment]
@ntorsen Again, thanks for thorough testing. :partying_face: 

- Changed the text on no results to: “No processes match your search criteria.”
- Added the active-filter-section to my-page and favourites-page.
- Fixed crash when you use your own user as a filter while on my-page.
- Fixed the search-field.
- Not sure why the font is misbehaving… I'll fix it later when upgrading some packages #354 

@ntorsen ready for testing https://web-vsm-test.radix.equinor.com

**Comment by ntorsen** [comment]
@SjoenH the fixes you put in are working good 💪
Font is still misbehaving, but this seems to only be the case for TEST environment.

**Comment by SjoenH** [comment]
Ready for testing in QA. @knudsvik @askbulle

**Comment by SjoenH** [comment]
:bowing_man: Thanks for testing!

> When a filter is added, either user filter or label filter, adding a new label/user should be done from a filtered list (only showing alternatives that are available - returning results)

I believe this can be done, but might introduce unneeded complexity and extra requests that might slow things down…
Maybe we should consider moving this to its own feature as well?

What do you think? @knudsvik Do you consider this a blocker?

**Comment by knudsvik** [comment]
> What do you think? @knudsvik Do you consider this a blocker?

@SjoenH No let's make it as another issue..
