### ISSUE TITLE
SQL performance concerns

### ISSUE THREAD

**Issue by Magos** [equinor/MAD-VSM-WEB#402]
During our demo, there were a lot of new VSMs being created, etc., and performance issues were noticed. App insights indicated SQL Server was taking most of this time.

Currently, Flyt's SQL database is using a pricing model aimed at a predictable cost, while more performance/scaling-oriented options are available. Look into the options with @pagodo.

- [ ] https://github.com/equinor/MAD-VSM-WEB/issues/415

**Comment by Magos** [comment]
Had a discussion with Peder today. Our conclusions from that were

- Upgrading the prod and QA levels to a premium DTU-based pricing level makes sense as an immediate step. Dev and Test could possibly be downgraded to Basic.
- We don't have experience in the team with using the vCore based pricing model as a performance tool.
- We should look at a "store process state" operation that involves fewer individual round-trips to the database and locks fewer things in the DB, for a longer-term solution.

**Comment by SjoenH** [comment]
👋 @anheri, you upgraded the DTU from 100 to 400 today? Is that correct?
What is the cost of this change?

**Comment by SjoenH** [comment]
We talked a bit about changing the structure to a mathematical graph: Nodes + Edges... would that improve things here?

This is also something that @SjoenH in front-end wish for the future.... 👼

**Comment by anheri** [comment]
> 👋 @anheri, you upgraded the DTU from 100 to 400 today? Is that correct? What is the cost of this change?

yes, pricing goes from about NOK 1000 to NOK 4000 per month

**Comment by anheri** [comment]
> We talked a bit about changing the structure to a mathematical graph: Nodes + Edges... would that improve things here?
> 
> This is also something that @SjoenH in front-end wish for the future.... 👼

It will not have any effect on speed... As the performance issue is the database... And I cannot see refactoring that to nodes+edges.
Generally, relational databases is terrible at storing graph data... often document databases is a better fit...

**Comment by SjoenH** [comment]
Yes, today we have a relational database. Exposing the relational DB as a graph wouldn't improve performance unless we change the underlying structure. 👍 

But as an API consumer, it would be more intuitive to work with Nodes and Edges. We'll have to talk about if it makes sense to change this now, or at all. I don't think we should change it for performance reasons, but for usability reasons.

I've already started translating that JSON over to Nodes and Edges in the front end... but it would be better to have it done in the back end. ref #296

**Comment by anheri** [comment]
After some fiddling with the servers. Found that it is not only the sql server that is underpowered, but also the appservice running the api. Increasing the to a P3V3 (top notch) server on the api the number come out to:

**Load at 100 users P3V3:**
Througput/Requests per second: 88,7
Latency: 700ms

**Load at 100 users S3 (current):**
Througput/Requests per second: drops linear to 0,7
Latency: 20 sec

**Comment by SjoenH** [comment]
@anheri thanks for exploring this. 

Is there any need for refactoring/improving the code? 

This is only for the create process endpoint, right?

**Comment by anheri** [comment]
> @anheri thanks for exploring this.
> 
> Is there any need for refactoring/improving the code?
> 
> This is only for the create process endpoint, right?

I have only explored the create process endpoint... as that seems to be causing crashes...

As for refactoring, I think a very easy thing to do is to return noContent on the create, saving the retrievel, which is'nt really used by the client anyway.

Long term:

- I think moving to CosmosDb should be considered, allthough it will require some serious effort. But IMHO it is a much better fit for tree/graph structured data. As the write is a O(1) operation. But probably to late for that sort of refactor.
- I'm a bit surprised that the changetracker on the VsmContext is turned of globally. I prefer to turn it off for read operations only. This could be the reason for needing this 5 iteration loop on the Save method trying to resolve conflict. Maybe @pagodo could shed some light on the reason for this loop to solve conflicts, but in general I would think that if there is a conflict there is little you can do about that and should just return the conflict to the client, whick should refresh the data and try again...

**Comment by SjoenH** [comment]
@Magos @pagodo @anheri @knudsvik Let's have a talk about this sometime. I'll try to schedule a meeting.

**Comment by SjoenH** [comment]
@anheri Could you post your findings and your recommended upgrade path? And how much that would cost?

**Todos**
Now:
- [ ] Upgrade compute and storage

Short-term:
- [ ] Fix the Create new process endpoint

**Comment by anheri** [comment]
### Load test - simulating ramp up of  0 users to 100 user

### AppService: S1 (Standard), Sql: Dtu 100 (today's spec)
Cost: NOK 600 + 900 = NOK 1500 per month
![image](https://user-images.githubusercontent.com/43775796/165291317-48f307a5-5224-4c72-b585-66a9c13a5719.png)


### AppService: P3V3, Sql: Dtu 400 
Cost: NOK 4300 + 3700 = NOK 8000 per month
![image](https://user-images.githubusercontent.com/43775796/165291549-27b35dcc-0d3f-4a97-890a-a539731e630a.png)

### Conclusion
(Blue line is simulated number of users)
Current server spec: seems to small. At current spec througput drops immediately as load increases. Latency increases rapidly.

Scaled up environment: Throughput follows linearly increase in load. Latency is well below 1 sec. at 80 users. At 100 users the application will still work, but latency is increasing.

**Comment by knudsvik** [comment]
Am a little bit confused about the pricing here. Earlier we were told an upgrade from 400,- NOK per month to 3.000,- pr month would suffice. The comment above says 1.500,- and 8.000,- per month respectively?

**Comment by anheri** [comment]
> 

So the quote of NOK 400 was not entirely accurate... that is for the app-service, not taking into account the upgrade of the sql server.

So the current cost: 
appservice S1: NOK 400 per month
sql server dtu 100: NOK 927 per month

upgraded environment:
appservice P3V3: NOK 4300 per month
sql server 400 dtu: NOK 3700 per month

**Comment by knudsvik** [comment]
Thanks @anheri . And both of these needs to be upgraded to get the performance boost?

**Comment by anheri** [comment]
yes

**Comment by anheri** [comment]
but offcourse you can slice it in half by doing: 
appservice: P1V3
sql server: 200 dtu

**Comment by anheri** [comment]
as we're moving to graph database.. these is no longer relevant
